apiVersion: apps/v1
kind: Deployment
metadata:
  name: pitstop-duration-optimizer
  labels:
    app: pitstop-duration-optimizer
    team: f1-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitstop-duration-optimizer
  template:
    metadata:
      labels:
        app: pitstop-duration-optimizer
        team: f1-demo
    spec:
      containers:
        - name: pitstop-duration-optimizer
          image: {{.Values.image}}
          ports:
            - containerPort: 7001
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 7001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7001
            initialDelaySeconds: 5
            periodSeconds: 10
