apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-analytics
  labels:
    app: driver-analytics
    team: f1-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-analytics
  template:
    metadata:
      labels:
        app: driver-analytics
        team: f1-demo
    spec:
      containers:
        - name: driver-analytics
          image: {{.Values.image}}
          ports:
            - containerPort: 7002
          env:
            - name: PITSTOP_SERVICE_URL
              value: "http://pitstop-duration-optimizer:7001"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 7002
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7002
            initialDelaySeconds: 5
            periodSeconds: 10
